apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      volumes:
        - name: backstage-config
          configMap:
            name: backstage-cm
      containers:
        - name: backstage
          image: quay.io/bhouse/backstage-app:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: backstage-config
              mountPath: /config

